### ISSUE TITLE
Deeper World Datapack

### ISSUE THREAD

**Issue by LKD-PIX** [NewJumper/DenseOres#3]
Is there a way to adjuste the dense ore distribution i can't seem to find any documentation on how to do this via a datapack.
I am trying to reconfigure this for a -512 deep world

**Comment by NewJumper** [comment]
There is no configuration available. I will work on it soon!

**Comment by NewJumper** [comment]
Due to how ores are generated (using jsons), you should be able to overwrite generation settings. So no config needed, all you need is a datapack which modifies the placement of the ores.
This mod's placed features are found [here](https://github.com/NewJumper/DenseOres/tree/master/src/generated/resources/data/denseores/worldgen/placed_feature).
Duplicate the file and change the y-values as needed and make sure to put the files in `resources/data/denseores/worldgen/placed_feature/`
